version: "3.4"
services:
    frontend:
        build:
            context: ./frontend
        #image: frontend:latest
        container_name: frontend
        hostname: frontend
        ports:
            - "80:8080"
        depends_on:
            - backend
    backend:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        build: 
            context: ./backend
        #image: backend:latest
        container_name: backend
        hostname: backend
        ports:
            - "5000:80"
            - "44349:443"
        networks:
            - overlay
        extra_hosts:
            - "DEMOTEST:10.0.75.1"  
networks:
  overlay: